import './styles.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body>
                <div id="img_landschaft" style={{backgroundImage: "url('/Landschaft_Portfolio.jpg')"}}></div>
                <div id="img_landschaft_cover">
                    <div id="img_landschaft_left">
                        <div id="img_landschaft_left_foto"></div>
                    </div>
                    <div id="img_landschaft_right">
                        <div id="img_landschaft_right_top">
                            <a href="#" className="ilrt_text">Github</a>
                            <a href="#" className="ilrt_text">E-Mail</a>
                            <a href="#" className="ilrt_text">Instagram</a>
                        </div>
                        <div id="img_landschaft_right_middle">
                            <div className="ilrm_text">Manuel</div>
                            <div className="ilrm_text">Bürki</div>
                        </div>
                        <div id="img_landschaft_right_bottom">
                            <div className="ilrb_text" >Willkommen auf <br /> meiner Webseite</div>
                        </div>
                    </div>
                </div>
                {children}
                <h1>footer</h1>
            </body>
        </html>
    )
}